import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — GlowUpp",
  description: "The terms that apply to using GlowUpp.",
};

export default function TermsOfServicePage() {
  return (
    <div className="flex flex-1 flex-col bg-zinc-50 px-6 py-16 dark:bg-black">
      <div className="mx-auto w-full max-w-3xl">
        <Link href="/" className="text-sm text-zinc-500 hover:underline dark:text-zinc-400">
          ← Back to GlowUpp
        </Link>

        <h1 className="mt-6 text-3xl font-semibold text-zinc-900 dark:text-zinc-50">
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-zinc-500 dark:text-zinc-400">Last updated: 20 September 2026</p>

        <div className="mt-10 space-y-10 text-zinc-700 dark:text-zinc-300">
          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">1. Who we are</h2>
            <p>
              GlowUpp (glowupp.co.uk) is operated by Dominik Wierzchowski, trading as GlowUpp, a
              sole trader based at 65 Sandway Crescent, Liverpool, L11 2SW, United Kingdom
              (&ldquo;GlowUpp&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;). Contact:{" "}
              <a href="mailto:domer2103@gmail.com" className="underline">domer2103@gmail.com</a>.
              By creating an account or using GlowUpp, you agree to these terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">2. What GlowUpp is</h2>
            <p>
              GlowUpp is a tool that lets homeowners upload photos of their space and generate
              AI-assisted design visualisations of possible renovations. Once you&rsquo;re happy
              with a design, GlowUpp optionally lets you request quotes from independent
              professionals (tradespeople/contractors) to bring it to life.
            </p>
            <p>
              GlowUpp is not a construction company, architect, or tradesperson, and does not
              itself carry out any building or design work.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">3. Eligibility and your account</h2>
            <ul className="list-disc space-y-2 pl-5">
              <li>You must be 18 or over to create an account.</li>
              <li>You&rsquo;re responsible for keeping your login details secure and for activity on your account.</li>
              <li>You must provide accurate information, including your address once shared for a project.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">4. AI-generated designs</h2>
            <p>
              Design visualisations are generated by AI models and are illustrative only. They are
              not architectural plans, structural assessments, planning-permission advice, or a
              guarantee that a design is buildable, compliant with building regulations, or
              achievable at any particular cost. Always get advice from a qualified professional
              before starting any building work.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">5. Quotes and professionals</h2>
            <ul className="list-disc space-y-2 pl-5">
              <li>
                If you request quotes, GlowUpp connects you with independent professionals. Any
                contract for work — price, scope, timeline, payment — is directly between you and
                that professional. GlowUpp is not a party to it.
              </li>
              <li>
                We don&rsquo;t vet, guarantee, or take responsibility for the quality, safety,
                licensing, or insurance of any professional&rsquo;s work. Do your own checks
                (references, insurance, trade body membership) before hiring anyone.
              </li>
              <li>
                GlowUpp does not currently process any payments between homeowners and
                professionals — no money moves through the platform.
              </li>
              <li>
                GlowUpp may charge participating professionals a fee for leads generated through
                the platform. Please don&rsquo;t use GlowUpp to arrange work with a professional
                and then take the relationship off-platform specifically to avoid this — it&rsquo;s
                how we keep the service running and free for homeowners.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">6. Acceptable use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc space-y-2 pl-5">
              <li>Upload content you don&rsquo;t have the right to use, or that&rsquo;s unlawful, abusive, or infringes someone else&rsquo;s rights.</li>
              <li>Use GlowUpp to harass, defraud, or mislead other users.</li>
              <li>Attempt to disrupt, reverse-engineer, or gain unauthorised access to GlowUpp&rsquo;s systems.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">7. Your content</h2>
            <p>
              You keep ownership of photos and content you upload. By uploading, you give GlowUpp
              a licence to use it solely to provide the service to you (e.g. generating your
              visualisations, sharing relevant details with professionals you choose to contact).
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">8. Disclaimers and liability</h2>
            <p>
              GlowUpp is provided &ldquo;as is&rdquo;, without warranties of any kind, to the
              fullest extent permitted by law. We don&rsquo;t exclude liability for things that
              can&rsquo;t legally be excluded (like death or personal injury caused by our
              negligence, or fraud). Beyond that, GlowUpp&rsquo;s liability to you for any claim
              arising from your use of the service is limited to the greater of £100 or the
              amount (if any) you&rsquo;ve paid us in the 12 months before the claim.
            </p>
            <p>
              We&rsquo;re not liable for the acts, omissions, or work quality of any professional
              you engage with through GlowUpp.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">9. Ending your account</h2>
            <p>
              You can stop using GlowUpp and ask us to delete your account at any time. We may
              suspend or end accounts that breach these terms or misuse the service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">10. Changes to these terms</h2>
            <p>
              We may update these terms as GlowUpp develops. We&rsquo;ll update the &ldquo;last
              updated&rdquo; date above when we do, and try to flag material changes directly.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">11. Governing law</h2>
            <p>These terms are governed by the law of England and Wales, and any disputes will be handled by the courts of England and Wales.</p>
          </section>

          <p className="border-t border-zinc-200 pt-6 text-sm text-zinc-500 dark:border-zinc-800 dark:text-zinc-400">
            GlowUpp is currently operated as a sole trader business, early in development. These
            terms aim to be plain and fair rather than exhaustive — see also our{" "}
            <Link href="/privacy" className="underline">Privacy Policy</Link>.
          </p>
        </div>
      </div>
    </div>
  );
}
